### ISSUE TITLE
Add option to assume each file runs in a transaction

### ISSUE THREAD

**Issue by sergio91pt** [sbdchd/squawk#106]
There are some migration tools like flyway that run each file in a separate transaction. With new rules being added, it seems clear now that just excluding prefer-robust-stmts is sub-optimal and it would be nice to have a flag in squawk to specify that each file is run within a separate transaction.

**Comment by sbdchd** [comment]
I think it shouldn't be too hard to add a flag that forces squawk to assume every file is wrapped in a transaction. Not sure what to call the flag, something like '--wrap-transaction'.

One option in the meantime is to manually add the begin and commit statements before passing the SQL to squawk. 

I'm curious how flyaway handles migrations that create indexes concurrently, which can't run in a transaction.

**Comment by sergio91pt** [comment]
:thought_balloon: Some alternatives would be '--assume-in-transaction' or '--executes-in-transaction' 

Flyway [uses regular expressions](https://github.com/flyway/flyway/blob/06106775909d6d9988bf1d89cd6193b2875ac1f8/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLParser.java#L100) to detect if it can run in a transaction. By [default](https://flywaydb.org/documentation/configuration/parameters/mixed) it does not allow to mix non-transactional and transactional statements in the same file.

**Comment by chdsbd** [comment]
I was looking into adding this feature and I think there's two ways to do it:

1. update all the lints to take an extra, `assume_transaction` argument.
2. add "BEGIN" and "COMMIT" to the input text.

For "1", there'd be a large maintenance burden. For "2", the line numbers would be not match the files in readouts.

My suggestion is to use a script to add "BEGIN" and "COMMIT" to your SQL before calling Squawk.

**Comment by chdsbd** [comment]
Closing this because I there aren't any plans to add this. As a workaround users can wrap their SQL with BEGIN and COMMIT before calling Squawk.
