### ISSUE TITLE
Allow passing in postgres version

### ISSUE THREAD

**Issue by sbdchd** [sbdchd/squawk#109]
`adding-field-with-default` only affects older versions of postgres so rather than have people disable it manually, we should allow them to pass in their desired postgres version.

For now we could exclude `adding-field-with-default` manually.

Possibly param name:

```
squawk --pg-major-version=13
squawk --pg-version=13
squawk --postgres-version=13
squawk --postgres-major-version=13
```

**Comment by chdsbd** [comment]
Fixed via #219. Squawk 0.14.0 includes this new feature.


```
squawk --pg-version 11.0 example.sql
```
