### ISSUE TITLE
Squawk schema failed to parse Postgres response (Partition of) 

### ISSUE THREAD

**Issue by jdsada30** [sbdchd/squawk#145]
I tried to parse the following query:
>CREATE TABLE measurement_y2006m02 PARTITION OF measurement
    FOR VALUES FROM ('2006-02-01') TO ('2006-03-01');

I expected this query to parse correctly, as it is supported by  for example PostgreSQL. 
I get the following linting error instead:

>Problem linting SQL files: Squawk schema failed to parse Postgres response. This indicates a bug with Squawk. Please report this error to https://github.com/sbdchd/squawk. Schema error: missing field `tableElts` at line 1 column 553

This query comes from the official PostgreSQL [documentation](https://www.postgresql.org/docs/10/ddl-partitioning.html). I found this by executing queries from GitHub project:  [vertx-jooq](https://github.com/jklingsporn/vertx-jooq)

I am using squawk version 0.7.0

**Comment by chdsbd** [comment]
@jdsada30 Thanks for the report! I'll take a look at fixing the internal Postgres schema

**Comment by chdsbd** [comment]
I've released a fix in v0.7.1 on npm.
