### ISSUE TITLE
Add a CONTRIBUTING.md file if contributions are welcome

### ISSUE THREAD

**Issue by adamrdavid** [sbdchd/squawk#181]
Are y'all welcoming contributions?

Would you like to have a CONTRIBUTING.md?

Examples: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#examples-of-contribution-guidelines

**Comment by chdsbd** [comment]
Hey @adamrdavid

Contributions are very welcome! I'll take a look at adding a CONTRIBUTING.md soon
