### ISSUE TITLE
adding-field-with-default is still valid on Postgres >= 11

### ISSUE THREAD

**Issue by froque** [sbdchd/squawk#200]
In https://squawkhq.com/docs/adding-field-with-default/ it says 
> This lint only applies to Postgres versions less than 11.

This is not absolutely true. 

From https://www.postgresql.org/docs/14/sql-altertable.html#SQL-ALTERTABLE-NOTES

> When a column is added with ADD COLUMN and a non-volatile DEFAULT is specified, the default is evaluated at the time of the statement and the result stored in the table's metadata. That value will be used for the column for all existing rows. If no DEFAULT is specified, NULL is used. In neither case is a rewrite of the table required.
>
>Adding a column with a volatile DEFAULT or changing the type of an existing column will require the entire table and its indexes to be rewritten. As an exception, when changing the type of an existing column, if the USING clause does not change the column contents and the old type is either binary coercible to the new type or an unconstrained domain over the new type, a table rewrite is not needed; but any indexes on the affected columns must still be rebuilt. Table and/or index rebuilds may take a significant amount of time for a large table; and will temporarily require as much as double the disk space.

And from the author:
https://www.2ndquadrant.com/en/blog/add-new-table-column-default-value-postgresql-11/
> Volatile expressions such as random() will still result in table rewrites 

Please update this rule for any of:
 - Remove Postgres version information 
 - Check for volatile defaults

To check if a function is volatile:
 https://stackoverflow.com/a/54453132/3929185
```
select proname, pronamespace::regnamespace, provolatile
from pg_proc
where proname = 'translate'

  proname  | pronamespace | provolatile 
-----------+--------------+-------------
 translate | pg_catalog   | i
(1 row) 
```
> provolatile tells whether the function's result depends only on its input arguments, or is affected by outside factors. It is i for “immutable” functions, which always deliver the same result for the same inputs. It is s for “stable” functions, whose results (for fixed inputs) do not change within a scan. It is v for “volatile” functions, whose results might change at any time.

**Comment by chdsbd** [comment]
release [v0.10.0](https://github.com/sbdchd/squawk/releases/tag/v0.10.0) fixes the documentation for this issue.

Squawk doesn't connect to Postgres, so it can't determine if a default is non-volatile.
