### ISSUE TITLE
Support configuration files

### ISSUE THREAD

**Issue by mercxry** [sbdchd/squawk#205]
Hello, I would like to have a configuration file that allows me to define some rules to exclude within the project, for example, I don't care about `require-concurrent-index-creation` and `require-concurrent-index-deletion`.

I would like to disable those at a project level without specifying those rules every time on the command, although I've never used squabble I like [their approach](https://github.com/erik/squabble#configuration) to this, especially being able to detect the file at the git root (`(git_repo_root)/.squabblerc`).

I'm open to work on this in my free time if you accept contributions 🙂

**Comment by sbdchd** [comment]
Yeah this works for me!

I think in terms of priority, passing an argument as a command line flag should take precedence over the config file

and for config file format, what were you thinking? I’m partial to toml but open to other ideas

**Comment by mercxry** [comment]
Yeah, definitely CLI arguments should take the priority

I have a strong preference for toml files, but I don't particularly mind other formats
