### ISSUE TITLE
Error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by Odas0R** [sbdchd/squawk#212]
After running `squawk` I get this error:

```bash
/home/odas0r/.nvm/versions/node/v18.1.0/lib/node_modules/squawk-cli/js/binaries/squawk: error while loading shared libraries: libssl.so.1.1: cannot open shared object file:
 No such file or directory
```

Can't really know for sure what's happening here...

I'm on Pop!_OS 22.04 LTS

**Comment by sbdchd** [comment]
Hmm weird, surprised it can’t find libssl

**Comment by Odas0R** [comment]
Found a fix by following this: https://askubuntu.com/questions/1126893/how-to-install-openssl-1-1-1-and-libssl-package#1127228

Found out that most distros don't have openssl1.1.1 which is required from `squawk-cli`

**Comment by nbx3** [comment]
This problem relates to Ubuntu 22.04 and also Pop!_OS 22.04 which is a respin so a more applicable way of resolving it is described here - https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di
