### ISSUE TITLE
Husky & lint-staged integration?

### ISSUE THREAD

**Issue by wmac9** [sbdchd/squawk#255]
Hey!  Love this tool!  Is there any plan to add functionality around husky and lint-staged? 

Currently trying to run squawk as a pre-commit hook using husky and lint-staged, the command does not run and/or does not post an exit code or resolve.  I'm not sure which but just wondering what y'all's plans are there?

**Comment by chdsbd** [comment]
Hey @wmac9,
We’re definitely open to making changes to support different Squawk workflows.

Do you have an example of what you’re trying to do and what needs to change in Squawk to support that?

**Comment by aldenquimby** [comment]
@chdsbd here's a demo of the issue: https://github.com/aldenquimby/squawk-255-demo

**Comment by chdsbd** [comment]
@aldenquimby Maybe this is related to #265

**Comment by chdsbd** [comment]
I'm trying to debug this. Seems like it might be related to this issue: https://github.com/okonet/lint-staged/issues/1019

#265 was fixed

**Comment by aldenquimby** [comment]
@chdsbd everything is working for me now that #265 is fixed - thank you!
