### ISSUE TITLE
prefer-big-int should have an option to ignore smallint

### ISSUE THREAD

**Issue by aldenquimby** [sbdchd/squawk#272]
## Background
- Our team typically prefers bigint over int, so `prefer-big-int` is great
- But sometimes, when we _know_ a number should be small, we want to use `smallint`. Examples:
    - `rank` in a list where we enforce the list is under 100 or 1000 long
    - `age`
    - `page_size_in_inches`
    - `tree_depth`
    - ... etc ...

## Ideas
1. [recommended] separate the current rule into `prefer-bigint-over-int` and `prefer-bigint-over-smallint`
2. remove `smallint` from the existing rule (and [update the docs](https://squawkhq.com/docs/prefer-big-int) making that explicit)
3. add a parameter to existing rule to control smallint behavior (do any rules accept params yet?)
4. allow disabling rules via SQL comments, similar to `// eslint-disable-next-line no-any-type`

**Comment by aldenquimby** [comment]
@sbdchd I'd be happy to put up a PR for this. What are your thoughts on the proposed ideas? Is there another direction you'd recommend going? Thank you!

**Comment by sbdchd** [comment]
yeah I'm open to a PR

I think option 1 works, but we have to be mindful of backwards compatibility so probably need to keep the old alias around for the near future


also SQL comments is appealing but the underlying parsing library we use doesn't support comments yet https://github.com/sbdchd/squawk/issues/149

**Comment by aldenquimby** [comment]
@sbdchd here you go! #273
