### ISSUE TITLE
0.19.0 requires libssl3 - does not run on earlier versions of Ubuntu

### ISSUE THREAD

**Issue by jgilchrist** [sbdchd/squawk#275]
Hi @sbdchd - love the project!

We are getting an issue since the release of `0.19.0` yesterday. It looks to me like the issue is that the binary was built on a very recent version of Ubuntu and as such is expecting libssl 3. The version of Ubuntu our runners are using still only has libssl 1, so we are getting the following error:

> /usr/local/lib/node_modules/squawk-cli/js/binaries/squawk: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

We've downgraded temporarily to `0.16.0` which works fine for us in the meantime (presumably that's because it was released before Github upgraded their runners to a version of Ubuntu that uses libssl3 by default), but long term it would be great if Squawk ran on systems that do not have libssl3 available.

**Comment by chdsbd** [comment]
We should probably pin our GitHub Actions runner to an earlier version: https://github.com/sbdchd/squawk/blob/master/.github/workflows/rust.yml#L21
