### ISSUE TITLE
`upload-to-github` could remove the existing comment once the validations are fixed

### ISSUE THREAD

**Issue by wmartins** [sbdchd/squawk#328]
As a follow up of #326, one thing I'm missing on my workflow is for Squawk to remove the created comment once all the fixes are in place.

Here's my current workflow:

- We write a migration
- We have a check that runs `squawk upload-to-github`
- If there are any errors we fix it and commit again

After all the fixes are there, we're still seeing a stale comment with the old violations.

### Initial investigation

I think this is currently happening because when there are no violations, we just return here:

https://github.com/sbdchd/squawk/blob/ddeed0259117329601e158a9655d6e9735af29ba/cli/src/subcommand.rs#L144-L147

### Suggestion

Maybe we could expand `comment_on_pr` to take care of removing a comment conditionally?

https://github.com/sbdchd/squawk/blob/ddeed0259117329601e158a9655d6e9735af29ba/github/src/lib.rs#L55-L80

**Comment by chdsbd** [comment]
Good idea. I think it'd be good to change the behavior to either delete the comment, or at least remove the violation messages in the comment

**Comment by chdsbd** [comment]
I've merged #330. Now Squawk will always leave a comment if it checks files. So the Squawk comment on a pull request should include updated violation messages

**Comment by wmartins** [comment]
I forgot to mention, but this is working like a charm @chdsbd! Thank you very much, I'll consider this closed.
