### ISSUE TITLE
Upgrade lib_pgquery to latest

### ISSUE THREAD

**Issue by sbdchd** [sbdchd/squawk#340]
https://pganalyze.com/blog/pg-query-postgres-16

should unlock windows support, also might be wise to switch to the protobuf based parsing instead of having to mess with json and serde

**Comment by SrMatheus2000** [comment]
Any update on this issue?

**Comment by lubo** [comment]
Shouldn't have this been closed by #356?

**Comment by chdsbd** [comment]
You're right!
This is resolved by #356
