### ISSUE TITLE
Update sqlalchemy docs for prefer-identity rule

### ISSUE THREAD

**Issue by ThomasWunderlich** [sbdchd/squawk#346]
The docs for the [prefer-identity rule](https://squawkhq.com/docs/prefer-identity) need to be updated since as of sqlalchemy 1.4
since as of sqlalchemy 1.4, there is built-in support for `IDENTITY`

**Comment by chdsbd** [comment]
Thank you for the report and the fix!

**Comment by ThomasWunderlich** [comment]
Closed by merging in #347
