### ISSUE TITLE
Dropping unique index concurrently is not supported 

### ISSUE THREAD

**Issue by teeyingyap** [sbdchd/squawk#366]
In the `disallowed-unique-constraint` rule, Squawk suggests to create and drop unique indexes concurrently but according to the Postgres [docs on "DROP INDEX"](https://www.postgresql.org/docs/current/sql-dropindex.html), a unique index cannot be dropped concurrently (but it can be created concurrently). 

> CONCURRENTLY
> There are several caveats to be aware of when using this option. Only one index name can be specified, and the CASCADE option is not supported. **(Thus, an index that supports a UNIQUE or PRIMARY KEY constraint cannot be dropped this way.)**

Given this Postgres limitation, I don't think the alembic downgrade example written in the docs works as intended.
```
def schema_downgrades():
    with op.get_context().autocommit_block():
        op.drop_index(
            op.f("dist_id_uniq"),
            postgresql_concurrently=True,
        )
```

### Solution:

For schema upgrade, we create the unique index for the constraint first, concurrently. Then use the created index to add the constraint.
For downgrade, we can just drop the constraint which also drops the index.
```
from alembic import op

def schema_upgrades():
    with op.get_context().autocommit_block():
        op.create_index(
            op.f("dist_id_uniq"),
            "distributors",
            ["dist_id"],
            unique=True,
            postgresql_concurrently=True,
        )
    op.execute(
        sa.text(
            """
            ALTER TABLE distributors ADD CONSTRAINT distributors_dist_id_key UNIQUE USING INDEX dist_id_uniq;
            """
        ),
    )
```

```
def schema_downgrades():
    op.drop_constraint(
        "distributors_dist_id_key",
        type_="unique",
    )
```
Happy to provide a PR to update the docs if you agree with this!

- https://squawkhq.com/docs/disallowed-unique-constraint/
- https://www.postgresql.org/docs/current/sql-dropindex.html

**Comment by sbdchd** [comment]
Ah good catch, a PR to update the docs makes sense!

We might also want to update the CLI to have a caveat about unique indexes as well

**Comment by teeyingyap** [comment]
About the caveat, I was mistaken. Once the index is bound to the constraint, it can’t be dropped. Nevertheless, I created a PR https://github.com/sbdchd/squawk/pull/370 to update the docs to be more clearer on how to create unique constraints without blocking read/writes.
