### ISSUE TITLE
Add Windows release binaries

### ISSUE THREAD

**Issue by TylerJang27** [sbdchd/squawk#374]
Hi! I was trying to install squawk on Windows (full download log [here](https://github.com/trunk-io/plugins/actions/runs/10638341991/job/29494318847?pr=858)), but it looks like your [install script](https://github.com/sbdchd/squawk/blob/master/js/install.js#L47-L69) relies on pulling binaries from the release assets. Currently there are only linux and darwin assets. Can you please add the relevant Windows downloads there as well?

**Comment by chdsbd** [comment]
This should be fixed in the latest release. Can you try installing via NPM and let me know how it works on Windows?

**Comment by TylerJang27** [comment]
Yep, this is working now! Thank you!
