### ISSUE TITLE
Nice to have: ability to tag certain migration files with exclusion rules

### ISSUE THREAD

**Issue by sudipidus** [sbdchd/squawk#394]
I have this case where I need to exclude 'ban-drop-table' for a use case (after verifying that table is not actually in use anymore in the code path)

Now I see 2 options to do this:
- supply exclusion rule in toml config
- or supply it in the command line argument

These configs seem to apply for all files. I see a way to include file in toml config but I can't link exclusion rule and migration file.

It would be super nice to have something like following:

*001_drop_unused_old_table.up.sql*
```
// Exclude: ban-drop-table
drop table if not exists my_unused_table
```
(Exclude tag (or something similar) is to be interpreted by the linter and apply that exclusion rule only to that particular file)

(submitting this for better triage, will consider checking this if it seems appropriate)

**Comment by sbdchd** [comment]
yeah it's something that we definitely need to do, there's https://github.com/sbdchd/squawk/issues/149 so going to close as dupe
