### ISSUE TITLE
Emit warning for char(n) datatype

### ISSUE THREAD

**Issue by nroi** [sbdchd/squawk#50]
Hi,

According to the [postgresql wiki](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_char.28n.29), there is almost never a good reason to use the `char(n)` datatype.

So I'm wondering if you would consider to include such a warning? Perhaps squawk is intended only for issues related to locking or breaking compatibility, but personally, I would find it very useful to have a linter in my CI pipeline that encourages general best practices related to DDL statements.

**Comment by sbdchd** [comment]
Yup I'm open to including more general lints.

Shouldn't be too hard to add.
